//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="http://dastugo.com/web_services/")]
    [System.SerializableAttribute()]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dastugo.com/web_services/", ConfigurationName="ServiceReferenceCogut.WebServiceCalc_2022_BSoap")]
    public interface WebServiceCalc_2022_BSoap {
        
        // CODEGEN: Generating message contract since element name firstname from namespace http://dastugo.com/web_services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/HelloWorld", ReplyAction="*")]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse HelloWorld(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse> HelloWorldAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://dastugo.com/web_services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/Calculator", ReplyAction="*")]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse Calculator(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse> CalculatorAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest request);
        
        // CODEGEN: Generating message contract since element name DivisionResult from namespace http://dastugo.com/web_services/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/Division", ReplyAction="*")]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse Division(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dastugo.com/web_services/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse> DivisionAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastname;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string firstname, string lastname) {
            this.firstname = firstname;
            this.lastname = lastname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculator", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequestBody Body;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class CalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondvalue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculatorRequestBody() {
        }
        
        public CalculatorRequestBody(int firstvalue, int secondvalue, string operation) {
            this.firstvalue = firstvalue;
            this.secondvalue = secondvalue;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatorResponse", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponseBody Body;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class CalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatorResult;
        
        public CalculatorResponseBody() {
        }
        
        public CalculatorResponseBody(string CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequestBody Body;
        
        public DivisionRequest() {
        }
        
        public DivisionRequest(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class DivisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public DivisionRequestBody() {
        }
        
        public DivisionRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisionResponse", Namespace="http://dastugo.com/web_services/", Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponseBody Body;
        
        public DivisionResponse() {
        }
        
        public DivisionResponse(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dastugo.com/web_services/")]
    public partial class DivisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceResponse DivisionResult;
        
        public DivisionResponseBody() {
        }
        
        public DivisionResponseBody(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceResponse DivisionResult) {
            this.DivisionResult = DivisionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalc_2022_BSoapChannel : WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalc_2022_BSoapClient : System.ServiceModel.ClientBase<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap>, WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap {
        
        public WebServiceCalc_2022_BSoapClient() {
        }
        
        public WebServiceCalc_2022_BSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalc_2022_BSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalc_2022_BSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalc_2022_BSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.HelloWorld(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string firstname, string lastname) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequestBody();
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse retVal = ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse> WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.HelloWorldAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldResponse> HelloWorldAsync(string firstname, string lastname) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.HelloWorldRequestBody();
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            return ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.Calculator(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public string Calculator(int firstvalue, int secondvalue, string operation) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequestBody();
            inValue.Body.firstvalue = firstvalue;
            inValue.Body.secondvalue = secondvalue;
            inValue.Body.operation = operation;
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse retVal = ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).Calculator(inValue);
            return retVal.Body.CalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse> WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.CalculatorAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest request) {
            return base.Channel.CalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorResponse> CalculatorAsync(int firstvalue, int secondvalue, string operation) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.CalculatorRequestBody();
            inValue.Body.firstvalue = firstvalue;
            inValue.Body.secondvalue = secondvalue;
            inValue.Body.operation = operation;
            return ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).CalculatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.Division(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest request) {
            return base.Channel.Division(request);
        }
        
        public WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceResponse Division(int a, int b) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse retVal = ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).Division(inValue);
            return retVal.Body.DivisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse> WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap.DivisionAsync(WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest request) {
            return base.Channel.DivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionResponse> DivisionAsync(int a, int b) {
            WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest inValue = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequest();
            inValue.Body = new WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.DivisionRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((WebFormApplicationForConsumingCalcWebService.ServiceReferenceCogut.WebServiceCalc_2022_BSoap)(this)).DivisionAsync(inValue);
        }
    }
}
